package pl.info.rkluszczynski.image.web.config;

public interface ConfigConstants {

    String WEB_APPLICATION_BASE_PACKAGE = "pl.info.rkluszczynski.image.web";


    String USER_SESSION_ATTRIBUTE_NAME__INPUT_IMAGE    = "userSessionInputImage";
    String USER_SESSION_ATTRIBUTE_NAME__TEMPLATE_IMAGE = "userSessionTemplateImage";
    String USER_SESSION_ATTRIBUTE_NAME__RESULT_IMAGE   = "userSessionResultImage";


    String STATUS_CONTEXT_PATH__ROOT = "/status";
    String COMPARE_CONTEXT_PATH__ROOT = "/compare";

    String COMPARE_CONTEXT_PATH__USER_SESSION_INPUT_IMAGE    = USER_SESSION_ATTRIBUTE_NAME__INPUT_IMAGE;
    String COMPARE_CONTEXT_PATH__USER_SESSION_TEMPLATE_IMAGE = USER_SESSION_ATTRIBUTE_NAME__TEMPLATE_IMAGE;
    String COMPARE_CONTEXT_PATH__USER_SESSION_RESULT_IMAGE   = USER_SESSION_ATTRIBUTE_NAME__RESULT_IMAGE;

}
